"""
AlgoNormalizer — Convert extracted strategy info into an AlgoBase-compatible Python class.
"""
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Any


def _make_template() -> str:
    """Return the algo template as a plain string (no .format() braces inside)."""
    return r'''"""
AlgoTrader -- Imported Algorithm: %%ALGO_ID%%
Source project: %%SOURCE_PROJECT%%
Strategy type: %%STRATEGY_TYPE%%
Auto-generated by import_project module on %%GENERATED_AT%%
"""
import uuid
import numpy as np
import pandas as pd
from typing import Dict, Any, List

from algos.base import AlgoBase
from data_sources.yf_fetcher import fetch_nifty_data
from utils.logger import (
    log_session_start, log_session_end, log_market_snapshot,
    log_signal_check, log_trade_entry, log_trade_exit, log_backtest_run
)

# -- Extracted constants from source -------------------------------------------
%%CONSTANTS_BLOCK%%

# -- Fallback defaults ---------------------------------------------------------
LOT_SIZE         = %%LOT_SIZE%%
INITIAL_CAPITAL  = %%INITIAL_CAPITAL%%


class %%CLASS_NAME%%(AlgoBase):
    algo_id = "%%ALGO_ID%%"
    name    = "%%ALGO_NAME%%"

    def run_backtest(self, start_date: str, end_date: str, interval: str = "1d") -> Dict[str, Any]:
        data = fetch_nifty_data(start_date, end_date, interval=interval)
        if data.empty:
            return {"metrics": self._metrics([], INITIAL_CAPITAL), "trades": [],
                    "monthly": {}, "equity_curve": []}

        data = data[data.index.dayofweek < 5]
        trades: List[Dict] = []
        total_pnl = 0.0
        wins = losses = 0

        for idx, row in data.iterrows():
            date_str = idx.strftime("%Y-%m-%d")
            log_session_start(self.algo_id, self.name, date_str, mode="backtest")

            open_px  = float(row["Open"])
            high_px  = float(row["High"])
            low_px   = float(row["Low"])
            close_px = float(row["Close"])
            strike   = round(open_px / 50) * 50

            # -- ENTRY LOGIC (extracted from source) ------------------------
            # Strategy type: %%STRATEGY_TYPE%%
            # Entry conditions detected: %%ENTRY_COUNT%%
            # Exit conditions detected: %%EXIT_COUNT%%

            signal = "NO_TRADE"
            opt_type = None
            entry_px = open_px
            exit_px = close_px
            pnl_val = 0.0
            exit_reason = "NO_TRADE"

            # TODO: Replace with actual extracted entry logic
            # Default placeholder: always take a paper trade for comparison
            signal = "IMPORTED_SIGNAL"
            opt_type = "CE"
            pnl_val = (close_px - open_px) * LOT_SIZE

            if signal != "NO_TRADE":
                won = pnl_val > 0
                tid = str(uuid.uuid4())[:8]
                log_trade_entry(
                    self.algo_id, tid, signal, open_px, strike, opt_type or "CE",
                    entry_px, f"{date_str} 09:20:00", LOT_SIZE,
                    context={"open": open_px, "close": close_px}
                )
                log_trade_exit(
                    self.algo_id, tid, f"{date_str} 15:25:00", exit_px,
                    "TARGET_EXIT" if won else "SL_EXIT", pnl_val,
                    round(pnl_val / (entry_px * LOT_SIZE) * 100, 2) if entry_px else 0,
                    context={"close": close_px}
                )
                trades.append({
                    "trade_id": tid, "algo_id": self.algo_id, "date": date_str,
                    "symbol": "NIFTY", "strike": strike,
                    "option_type": opt_type or "CE", "signal_name": signal,
                    "entry_time": f"{date_str} 09:20:00", "entry_price": entry_px,
                    "exit_time": f"{date_str} 15:25:00", "exit_price": exit_px,
                    "exit_reason": "TARGET_EXIT" if won else "SL_EXIT",
                    "pnl": round(pnl_val, 2), "lot_size": LOT_SIZE, "status": "closed",
                })
                total_pnl += pnl_val
                if won:
                    wins += 1
                else:
                    losses += 1
                log_session_end(self.algo_id, 1, pnl_val, status="OK")
            else:
                log_session_end(self.algo_id, 0, 0.0, status="NO_TRADE")

        pnl_list = [t["pnl"] for t in trades]
        if trades:
            wr = wins / len(trades) * 100
            log_backtest_run(self.algo_id, start_date, end_date, len(trades), wr, total_pnl)

        return {
            "metrics": self._metrics(pnl_list, INITIAL_CAPITAL),
            "trades": trades,
            "monthly": self._monthly_breakdown(trades),
            "equity_curve": self._equity_curve(trades),
            "signal_cards": {"Close": round(float(data.iloc[-1]["Close"]), 0)}
        }

    def get_live_signal(self, spot: float, indicators: Dict[str, float]) -> Dict[str, Any]:
        # TODO: Implement actual live signal logic from source
        return {
            "signal": "NO_TRADE",
            "option_type": None,
            "strike": None,
            "signal_cards": {"Spot": round(spot, 1)},
        }
'''


class AlgoNormalizer:
    """
    Takes extracted strategy info and generates a runnable AlgoBase class.
    The generated file is a TEMPLATE -- user must fill in actual entry/exit logic.
    """

    def __init__(self, extracted: Dict[str, Any], source_project: str):
        self.extracted = extracted
        self.source_project = source_project
        self.algo_id = self._make_algo_id()

    def _make_algo_id(self) -> str:
        """Create a unique algo_id like 'imported_niftybot_v2_0525'."""
        base = re.sub(r"[^a-z0-9]", "_", self.source_project.lower()).strip("_")
        ts = datetime.now().strftime("%m%d")
        return f"imported_{base}_{ts}"

    def _build_constants_block(self) -> str:
        """Format extracted numeric constants as Python assignments."""
        lines = []
        for name, val in self.extracted.get("constants", {}).items():
            # Only keep numeric constants (skip strings, objects)
            if isinstance(val, (int, float)):
                lines.append(f"{name:<20} = {val}")
        if not lines:
            lines.append("# No numeric constants extracted -- add manually")
        return "\n".join(lines)

    def generate(self) -> str:
        """Return the full Python source code as a string."""
        e = self.extracted
        lot_size = e.get("position_sizing") or 25
        capital = e.get("constants", {}).get("INITIAL_CAPITAL", 200_000)
        if isinstance(capital, str):
            capital = 200_000

        class_name = "".join(word.capitalize() for word in self.algo_id.split("_"))

        template = _make_template()
        return (template
            .replace("%%ALGO_ID%%", self.algo_id)
            .replace("%%ALGO_NAME%%", f"Imported: {self.source_project}")
            .replace("%%SOURCE_PROJECT%%", self.source_project)
            .replace("%%STRATEGY_TYPE%%", e.get("strategy_type", "unknown"))
            .replace("%%GENERATED_AT%%", datetime.now().isoformat())
            .replace("%%CONSTANTS_BLOCK%%", self._build_constants_block())
            .replace("%%LOT_SIZE%%", str(lot_size))
            .replace("%%INITIAL_CAPITAL%%", str(capital))
            .replace("%%CLASS_NAME%%", class_name)
            .replace("%%ENTRY_COUNT%%", str(len(e.get("entry_logic", []))))
            .replace("%%EXIT_COUNT%%", str(len(e.get("exit_logic", []))))
        )

    def save(self, output_dir: str = "imported_algos") -> str:
        """Save generated class to file and return the file path."""
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        fname = f"{self.algo_id}.py"
        fpath = out_dir / fname
        fpath.write_text(self.generate(), encoding="utf-8")
        return str(fpath)

    def print_next_steps(self):
        """Print instructions for the user."""
        print(f"\n{'='*60}")
        print(f"IMPORTED ALGO: {self.algo_id}")
        print(f"{'='*60}")
        print("\nNext steps to make this algo functional:")
        print("1. Open the generated file:")
        print(f"   imported_algos/{self.algo_id}.py")
        print("2. Replace the placeholder entry/exit logic in run_backtest()")
        print("   with actual conditions from the source project.")
        print("3. Implement get_live_signal() for paper trading.")
        print("4. Add the algo to config.py ALGOS dict:")
        print(f'   "{self.algo_id}": {{"id": "{self.algo_id}", "name": "Imported: {self.source_project}", ...}}')
        print("5. Run: python -m import_project.backtest_wrapper")
        print(f"{'='*60}")
